// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "POST";
    path: "/authentication";
    body: {
        email: string;
        password: string;
    };
    response: {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 401;
        information: "user.invalid.password";
        body?: undefined;
    } | {
        code: 200;
        information: "user.logged";
        body: string;
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
